name: Build LaTeX document
on:
  push:
    branches: master
    paths:
      - '**/*.tex'
      - './*.tex'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image and generate PDF
        run: |
          make docker

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          files: ./db.pdf
          tag_name: release-pdf
          name: Built PDF 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

